// Role data
const DEV_LOGIN_PASSWORD_HASH =
  '$2b$10$rWympviVCbsie490UxBN0u0kEc3Yz/A2C9AXGJv.5emb3NMhYtHMK';

export const SUPERADMIN_ROLES_DATA = [
  {
    id: 'cmmxj94yt0000a6j8qbuclr5v',
    name: 'super_admin',
    displayName: 'Super Admin',
    description: '',
    permissions: [
      'accounts:update',
      'accounts:manage',
      'accounts:view',
      'admission_results:update',
      'admission_results:export',
      'admission_results:import',
      'admission_results:manage',
      'admission_results:restore',
      'admission_results:create',
      'admission_results:view',
      'admission_results:delete',
      'posts:update',
      'posts:export',
      'posts:import',
      'posts:manage',
      'posts:restore',
      'posts:create',
      'posts:view_all',
      'posts:view_own',
      'posts:view',
      'posts:delete',
      'posts:publish',
      'comments:update',
      'comments:approve',
      'comments:export',
      'comments:manage',
      'comments:restore',
      'comments:create',
      'comments:view',
      'comments:delete',
      'settings:update',
      'settings:export',
      'settings:manage',
      'settings:create',
      'settings:view',
      'settings:delete',
      'categories:update',
      'categories:export',
      'categories:manage',
      'categories:create',
      'categories:view',
      'categories:delete',
      'dashboard:view',
      'groups:update',
      'groups:export',
      'groups:manage',
      'groups:create',
      'groups:view',
      'groups:delete',
      'contact_requests:update',
      'contact_requests:export',
      'contact_requests:assign',
      'contact_requests:manage',
      'contact_requests:restore',
      'contact_requests:create',
      'contact_requests:view',
      'contact_requests:delete',
      'users:active',
      'users:update',
      'users:export',
      'users:hard-delete',
      'users:import',
      'users:manage',
      'users:restore',
      'users:create',
      'users:unactive',
      'users:view',
      'users:delete',
      'page_contents:update',
      'page_contents:export',
      'page_contents:manage',
      'page_contents:create',
      'page_contents:view',
      'page_contents:delete',
      'sessions:update',
      'sessions:export',
      'sessions:manage',
      'sessions:restore',
      'sessions:revoke-by-user',
      'sessions:create',
      'sessions:view',
      'sessions:delete',
      'students:active',
      'students:update',
      'students:export',
      'students:import',
      'students:manage',
      'students:restore',
      'students:create',
      'students:view_all',
      'students:view_own',
      'students:view',
      'students:delete',
      'tags:update',
      'tags:export',
      'tags:manage',
      'tags:create',
      'tags:view',
      'tags:delete',
      'notifications:export',
      'notifications:manage',
      'notifications:view_all',
      'notifications:view_own',
      'notifications:view',
      'messages:update',
      'messages:export',
      'messages:manage',
      'messages:create',
      'messages:view',
      'messages:delete',
      'uploads:update',
      'uploads:export',
      'uploads:manage',
      'uploads:create',
      'uploads:view',
      'uploads:delete',
      'roles:update',
      'roles:export',
      'roles:manage',
      'roles:create',
      'roles:view',
      'roles:delete',
    ],
    isActive: true,
  },
  {
    id: 'cmmxj94yu0001a6j80p78qxqr',
    name: 'admin',
    displayName: 'Admin',
    description: null,
    permissions: [
      'dashboard:view',
      'posts:view',
      'posts:view_all',
      'posts:view_own',
      'posts:create',
      'posts:update',
      'posts:delete',
      'posts:publish',
      'posts:manage',
      'categories:view',
      'categories:create',
      'categories:update',
      'categories:delete',
      'categories:manage',
      'users:view',
      'users:create',
      'users:update',
      'users:delete',
      'users:manage',
      'notifications:view',
      'notifications:view_all',
      'notifications:view_own',
      'notifications:manage',
      'contact_requests:view',
      'contact_requests:create',
      'contact_requests:assign',
      'contact_requests:update',
      'contact_requests:delete',
      'contact_requests:manage',
      'accounts:view',
      'accounts:update',
      'sessions:view',
      'sessions:create',
      'sessions:update',
      'sessions:delete',
      'sessions:manage',
      'uploads:view',
      'uploads:create',
      'uploads:delete',
      'uploads:manage',
      'admission_results:view',
      'admission_results:create',
      'admission_results:update',
      'admission_results:delete',
      'admission_results:manage',
      'page_contents:view',
      'page_contents:create',
      'page_contents:update',
      'page_contents:delete',
      'page_contents:manage',
      'groups:view',
      'groups:create',
      'groups:update',
      'groups:delete',
      'groups:manage',
      'settings:view',
      'settings:manage',
      'settings:import',
      'settings:export',
      'settings:update',
    ],
    isActive: true,
  },
  {
    id: 'cmmylgrxq004wldj8uofhzeen',
    name: 'editor',
    displayName: 'Editor',
    description: '',
    permissions: [
      'posts:view',
      'posts:create',
      'posts:update',
      'posts:delete',
      'posts:export',
      'posts:import',
      'posts:manage',
      'posts:publish',
      'posts:restore',
      'posts:view_all',
      'posts:view_own',
      'accounts:view',
      'accounts:update',
      'accounts:manage',
      'dashboard:view',
      'uploads:view',
      'uploads:create',
      'uploads:update',
      'uploads:delete',
      'uploads:export',
      'uploads:manage',
      'categories:view',
      'categories:create',
      'categories:update',
      'categories:delete',
      'categories:export',
      'categories:manage',
      'tags:view',
      'tags:create',
      'tags:update',
      'tags:delete',
      'tags:export',
      'tags:manage',
      'contact_requests:view',
      'contact_requests:create',
      'contact_requests:update',
      'contact_requests:delete',
      'contact_requests:assign',
      'contact_requests:export',
      'contact_requests:manage',
      'contact_requests:restore',
      'page_contents:view',
      'page_contents:create',
      'page_contents:update',
      'page_contents:delete',
      'page_contents:export',
      'page_contents:manage',
    ],
    isActive: true,
  },
  {
    id: 'cmnfr1pnu000iy3j8psit0mgm',
    name: 'user',
    displayName: 'User',
    description: null,
    permissions: null,
    isActive: true,
  },
];

// User data
export const SUPERADMIN_USERS_DATA = [
  {
    id: 'cmmxj951o0002a6j80hysxdq0',
    email: 'superadmin@hub.edu.vn',
    name: 'Super Administrator',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
  {
    id: 'cmmxj951v0004a6j8h24tmaz4',
    email: 'admin@hub.edu.vn',
    name: 'Administrator',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: null,
    avatar: null,
    emailVerified: null,
    phone: null,
    address: null,
    isActive: true,
  },
  {
    id: 'cmmynf6dm0003rbj85j7dxyb6',
    email: 'lamvtt@hub.edu.vn',
    name: 'Thanh Lâm',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: '',
    avatar: null,
    emailVerified: null,
    phone: '',
    address: null,
    isActive: true,
  },
  {
    id: 'cmnfr1pql000jy3j8s7ghzrv7',
    email: 'thang.ph2146@gmail.com',
    name: 'Thắng Phạm',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: '',
    avatar:
      'https://lh3.googleusercontent.com/a/ACg8ocLhicj6TqxKzF0hVnmJ5OueMMe-zdEgZT_U9b3iIzjTQP3ZerqO=s96-c',
    emailVerified: null,
    phone: '',
    address: null,
    isActive: true,
  },
  {
    id: 'cmnzoz4oi009hyrj8fto16kbz',
    email: 'thangph@hub.edu.vn',
    name: 'Thang Pham Hoang',
    password: DEV_LOGIN_PASSWORD_HASH,
    bio: '',
    avatar:
      'https://lh3.googleusercontent.com/a/ACg8ocK8ybfPbsmaejqRrCM1q1hKxnsAi5KclkMWiMmEdb3Q2KveHw=s96-c',
    emailVerified: null,
    phone: '',
    address: null,
    isActive: true,
  },
];

// UserRole data
export const SUPERADMIN_USER_ROLES_DATA = [
  {
    id: 'cmmxj951s0003a6j8mc3f5wav',
    userId: 'cmmxj951o0002a6j80hysxdq0',
    roleId: 'cmmxj94yt0000a6j8qbuclr5v',
  },
  {
    id: 'cmmxj951z0005a6j8xx6y1zju',
    userId: 'cmmxj951v0004a6j8h24tmaz4',
    roleId: 'cmmxj94yu0001a6j80p78qxqr',
  },
  {
    id: 'cmnzoylht009fyrj8242ykupt',
    userId: 'cmmynf6dm0003rbj85j7dxyb6',
    roleId: 'cmmylgrxq004wldj8uofhzeen',
  },
  {
    id: 'cmnzoxpm1009ayrj8mmsl2n9i',
    userId: 'cmnfr1pql000jy3j8s7ghzrv7',
    roleId: 'cmmylgrxq004wldj8uofhzeen',
  },
  {
    id: 'cmnzozi2t009nyrj8gj2phwnf',
    userId: 'cmnzoz4oi009hyrj8fto16kbz',
    roleId: 'cmmylgrxq004wldj8uofhzeen',
  },
];
