"use client";
import type { ColumnDef, ColumnFiltersState, OnChangeFn, RowSelectionState } from "@tanstack/react-table";
import { Button } from "@ui/components/button";
import { AdminDataTable } from "@/components/admin-data-table";
import { RefreshCw, FilterX } from "lucide-react";
import type { ScreenRow } from "../types";
export function ScreensTable({ data, columns, isLoading, columnFilters, onColumnFiltersChange, globalFilter, onGlobalFilterChange, selectedRowIds, onSelectedRowIdsChange, total, onRefresh, onClearFilters, onBulkDelete, isFetching }: {
  data: ScreenRow[]; columns: ColumnDef<ScreenRow>[]; isLoading: boolean; columnFilters: ColumnFiltersState; onColumnFiltersChange: OnChangeFn<ColumnFiltersState>; globalFilter: string; onGlobalFilterChange: OnChangeFn<string>; selectedRowIds: RowSelectionState; onSelectedRowIdsChange: OnChangeFn<RowSelectionState>; total: number; onRefresh: () => void; onClearFilters: () => void; onBulkDelete: (rows: ScreenRow[]) => Promise<void>; isFetching?: boolean;
}) {
  return (<AdminDataTable<ScreenRow> data={data} getRowId={(r) => r.id} columns={columns} isLoading={isLoading} emptyLabel='Chưa có màn hình — bấm "Thêm màn hình".' columnFilters={columnFilters} onColumnFiltersChange={onColumnFiltersChange} globalFilter={globalFilter} onGlobalFilterChange={onGlobalFilterChange} globalFilterPlaceholder="Tìm theo tên..." filterToolbarExtra={<div className="flex flex-wrap items-center gap-2"><Button variant="outline" onClick={() => { void onRefresh(); }}><RefreshCw className={isFetching ? "size-4 animate-spin" : "size-4"} /> Làm mới</Button><Button variant="outline" onClick={onClearFilters}><FilterX className="size-4" /> Xóa bộ lọc</Button></div>} csvExport={{ fileName: "man-hinh.csv" }} rowSelectionEnabled selectedRowIds={selectedRowIds} onSelectedRowIdsChange={onSelectedRowIdsChange} bulkActions={[{ id: "bulk-screen-delete", label: "Xóa tạm đã chọn", variant: "destructive", confirm: { title: "Xóa màn hình?", description: (rows) => `${rows.length} màn hình sẽ vào thùng rác.`, confirmLabel: "Xóa tạm", destructive: true }, onAction: onBulkDelete }]} footer={<p className="text-sm text-muted-foreground">{isLoading ? "Đang tải..." : `Tổng ${total} màn hình`}</p>} />);
}
