"use client";
import type { ColumnDef, ColumnFiltersState, OnChangeFn, RowSelectionState } from "@tanstack/react-table";
import { Button } from "@ui/components/button";
import { AdminDataTable } from "@/components/admin-data-table";
import { AdminTablePaginationFooter } from "@/components/admin-table-pagination-footer";
import { FilterX, RefreshCw } from "lucide-react";
import type { CameraRow } from "../types";
export function CamerasTrashTable({ data, columns, isLoading, columnFilters, onColumnFiltersChange, globalFilter, onGlobalFilterChange, selectedRowIds, onSelectedRowIdsChange, page, pageSize, total, onPageChange, onPageSizeChange, onRefresh, onClearFilters, onBulkRestore, onBulkPurge, isFetching }: {
  data: CameraRow[]; columns: ColumnDef<CameraRow>[]; isLoading: boolean; columnFilters: ColumnFiltersState; onColumnFiltersChange: OnChangeFn<ColumnFiltersState>; globalFilter: string; onGlobalFilterChange: OnChangeFn<string>; selectedRowIds: RowSelectionState; onSelectedRowIdsChange: OnChangeFn<RowSelectionState>; page: number; pageSize: number; total: number; onPageChange: (p: number) => void; onPageSizeChange: (s: number) => void; onRefresh: () => void; onClearFilters: () => void; onBulkRestore: (rows: CameraRow[]) => Promise<void>; onBulkPurge: (rows: CameraRow[]) => Promise<void>; isFetching?: boolean;
}) {
  return (<AdminDataTable<CameraRow> data={data} getRowId={(r) => r.id} columns={columns} isLoading={isLoading} emptyLabel="Thùng rác trống." manualFiltering columnFilters={columnFilters} onColumnFiltersChange={onColumnFiltersChange} globalFilter={globalFilter} onGlobalFilterChange={onGlobalFilterChange} globalFilterPlaceholder="Tìm trong thùng rác..." filterToolbarExtra={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => { void onRefresh(); }}><RefreshCw className={isFetching ? "size-4 animate-spin" : "size-4"} /> Làm mới</Button><Button variant="destructive" onClick={onClearFilters}><FilterX className="size-4" /> Xóa bộ lọc</Button></div>} csvExport={{ fileName: "camera-thung-rac.csv" }} rowSelectionEnabled selectedRowIds={selectedRowIds} onSelectedRowIdsChange={onSelectedRowIdsChange} bulkActions={[{ id: "bulk-camera-restore", label: "Khôi phục", variant: "default", confirm: { title: "Khôi phục?", description: (_rows) => `${_rows.length} camera.`, confirmLabel: "Khôi phục" }, onAction: onBulkRestore }, { id: "bulk-camera-purge", label: "Xóa vĩnh viễn", variant: "destructive", confirm: { title: "Xóa vĩnh viễn?", description: () => `Không thể hoàn tác.`, confirmLabel: "Xóa vĩnh viễn", destructive: true }, onAction: onBulkPurge }]} footer={<AdminTablePaginationFooter page={page} pageSize={pageSize} total={total} isLoading={isLoading} onPageChange={onPageChange} onPageSizeChange={onPageSizeChange} emptySummary="Không có camera" itemLabel="camera" />} />);
}
