import { EditorThemeClasses } from "lexical"

export const editorTheme: EditorThemeClasses = {
  ltr: "editor-ltr",
  rtl: "editor-rtl",
  heading: {
    h1: "editor-h1",
    h2: "editor-h2",
    h3: "editor-h3",
    h4: "editor-h4",
    h5: "editor-h5",
    h6: "editor-h6",
  },
  paragraph: "editor-paragraph",
  quote: "editor-quote",
  link: "editor-link",
  list: {
    checklist: "editor-checklist",
    listitem: "editor-listitem",
    listitemChecked: "editor-listitem-checked",
    listitemUnchecked: "editor-listitem-unchecked",
    nested: {
      listitem: "editor-nested-listitem",
    },
    ol: "editor-ol",
    olDepth: [
      "editor-ol-depth-1",
      "editor-ol-depth-2",
      "editor-ol-depth-3",
      "editor-ol-depth-4",
      "editor-ol-depth-5",
    ],
    ul: "editor-ul",
    ulDepth: [
      "editor-ul-depth-1",
      "editor-ul-depth-2",
      "editor-ul-depth-3",
      "editor-ul-depth-4",
      "editor-ul-depth-5",
    ],
  },
  hashtag: "editor-hashtag",
  text: {
    bold: "editor-text-bold",
    code: "editor-text-code",
    italic: "editor-text-italic",
    strikethrough: "editor-text-strikethrough",
    subscript: "editor-text-subscript",
    superscript: "editor-text-superscript",
    underline: "editor-text-underline",
    underlineStrikethrough: "editor-text-underline-strikethrough",
  },
  textAlign: {
    left: "editor-text-align-left",
    center: "editor-text-align-center",
    right: "editor-text-align-right",
    justify: "editor-text-align-justify",
  },
  image: "editor-image",
  inlineImage: "editor-inline-image",
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-token--keyword",
    attr: "editor-token--attr-name",
    boolean: "editor-token--property",
    builtin: "editor-token--selector",
    cdata: "editor-token--comment",
    char: "editor-token--selector",
    class: "editor-token--function",
    "class-name": "editor-token--function",
    comment: "editor-token--comment",
    constant: "editor-token--property",
    deleted: "editor-token--property",
    doctype: "editor-token--comment",
    entity: "editor-token--operator",
    function: "editor-token--function",
    important: "editor-token--variable",
    inserted: "editor-token--selector",
    keyword: "editor-token--keyword",
    namespace: "editor-token--variable",
    number: "editor-token--property",
    operator: "editor-token--operator",
    prolog: "editor-token--comment",
    property: "editor-token--property",
    punctuation: "editor-token--punctuation",
    regex: "editor-token--variable",
    selector: "editor-token--selector",
    string: "editor-token--string",
    symbol: "editor-token--property",
    tag: "editor-token--property",
    url: "editor-token--operator",
    variable: "editor-token--variable",
  },
  table: "editor-table",
  tableCell: "editor-table-cell",
  tableCellActionButton: "editor-table-cell-action-button",
  tableCellActionButtonContainer: "editor-table-cell-action-button-container",
  tableCellEditing: "editor-table-cell-editing",
  tableCellHeader: "editor-table-cell-header",
  tableCellPrimarySelected: "editor-table-cell-primary-selected",
  tableCellResizer: "editor-table-cell-resizer",
  tableCellSelected: "editor-table-cell-selected",
  tableCellSortedIndicator: "editor-table-cell-sorted-indicator",
  tableResizeRuler: "editor-table-cell-resize-ruler",
  tableRowStriping: "editor-table-row-striping",
  tableSelected: "editor-table-selected",
  tableSelection: "editor-table-selection",
  layoutItem: "editor-layout-item",
  layoutContainer: "editor-layout-container",
  autocomplete: "editor-autocomplete",
  embedBlock: {
    base: "editor-embed-block",
    focus: "editor-embed-block-focused",
  },
  hr: "editor-hr",
}
